[package]
name = "rhythiophysm"
version = "0.1.0"
authors = ["JackRedstonia jackredstonia64@gmail.com"]
edition = "2018"
repository = "https://gitlab.com/JackRedstonia/rhythiophysm"
license = "MIT"

[dependencies]
stacks = { git = "https://gitlab.com/JackRedstonia/stacks" }